// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoTRGHvZv14pTw2Q58v7XgiIASTKJyL_M',
    appId: '1:431324925667:web:4fc8d0f7a7c86abb96ffd6',
    messagingSenderId: '431324925667',
    projectId: 'cheer-up-ddcb2',
    authDomain: 'cheer-up-ddcb2.firebaseapp.com',
    databaseURL: 'https://cheer-up-ddcb2-default-rtdb.firebaseio.com',
    storageBucket: 'cheer-up-ddcb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKlgm3SmlES0sm8zmiejw2ZXTI5J4BPKw',
    appId: '1:431324925667:android:3e58972b726cf20f96ffd6',
    messagingSenderId: '431324925667',
    projectId: 'cheer-up-ddcb2',
    databaseURL: 'https://cheer-up-ddcb2-default-rtdb.firebaseio.com',
    storageBucket: 'cheer-up-ddcb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe6GMhRGYEtt0oaSBSIMc66M4086xYJw0',
    appId: '1:431324925667:ios:78584280e70f5edd96ffd6',
    messagingSenderId: '431324925667',
    projectId: 'cheer-up-ddcb2',
    databaseURL: 'https://cheer-up-ddcb2-default-rtdb.firebaseio.com',
    storageBucket: 'cheer-up-ddcb2.appspot.com',
    iosClientId: '431324925667-tbh8rbjck26vq9qmfo8iloub1l4bh2mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.navegacao',
  );
}
